name: config_run_624
render: false
vis_debug: false
seed: 5
max_env_steps: 50
env:
  _target_: vtamp.environments.turtle.env.TurtleEnvEmbodied
  stability_check: False
  gui: true
task:
  _target_: vtamp.environments.turtle.env.DrawShape
  goal_str: "draw an arrow pointing to the largest object"
  task_name: Arrow
policy:
  _target_: vtamp.policies.llm3.policy.LLM3
  max_feedbacks: 5
  max_csp_samples: 10000
  gaussian_blur: true
  method: llm3-gaussian
updater:
  _target_: vtamp.environments.utils.DefaultUpdater