name: config_run_161
render: false
vis_debug: false
seed: 2
max_env_steps: 20
env:
  _target_: vtamp.environments.raven.env.RavenEnv
  stability_check: False
  gui: true
task:
  _target_: vtamp.environments.raven.tasks.PackingTask
  goal_str: "Place all of the blocks within a square region with a width and length of 0.16 in the center of the table"
  task_name: Packing
policy:
  _target_: vtamp.policies.code_as_policies.policy.CaP
  max_feedbacks: 0
  max_csp_samples: 1000
  gaussian_blur: false
  method: cap
updater:
  _target_: vtamp.environments.raven.env.RavenGroundTruthBeliefUpdater