name: config_run_670
render: false
vis_debug: false
seed: 1
max_env_steps: 20
env:
  _target_: vtamp.environments.raven.env.RavenEnv
  stability_check: False
  gui: true
task:
  _target_: vtamp.environments.raven.tasks.UnstackTask
  goal_str: "Put the green block in the green bowl"
  task_name: Unstack
policy:
  _target_: vtamp.policies.llm3.policy.LLM3
  max_feedbacks: 5
  max_csp_samples: 250
  gaussian_blur: true
  method: llm3-gaussian
updater:
  _target_: vtamp.environments.raven.env.RavenGroundTruthBeliefUpdater